### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by ghost** [olmokramer/atom-css-specificity#2]
[Enter steps to reproduce below:]
1. .Closed a tab. Nothing more, nothing less.

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [css-specificity](https://github.com/olmokramer/atom-css-specificity) package, v0.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /home/tec/.atom/packages/css-specificity/lib/css-specificity-status.js:59

TypeError: Cannot read property 'remove' of undefined
  at /home/tec/.atom/packages/css-specificity/lib/css-specificity-status.js:46:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:290:27)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:468:18)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.10.1
atom-image-resize, v0.3.0
atom-minify, v0.4.1
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
browser-plus, v0.0.34
css-specificity, v0.1.3
drop-base64-encoding, v0.2.0
language-svg, v0.9.0
less-autocompile, v1.0.0
linter, v1.5.2
linter-csslint, v1.0.5
linter-gcc, v0.3.8
linter-htmlhint, v0.1.1
linter-jshint, v1.2.0
linter-less, v2.1.0
linter-php, v1.0.3
linter-sass-lint, v0.1.4
linter-scss-lint, v2.0.0
minimap, v4.13.3
php-cs-fixer, v2.4.0
sass-autocompile, v0.9.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
Looking at this and [the other error](https://github.com/olmokramer/atom-css-specificity/issues/1), this seems to be related. Trying to narrow things down, it seems to be caused by the fact there was a tab named "untitled" (containing an empty, unsaved document). Upon launching, this tab was recreated – causing atom-css to fail, closing that tab and making sure that there is no such "untitled", unsaved document open in Atom upon launch seems to solve the issue all together.
